name: neur0flow
version: ${version}
main: dev.neur0pvp.neur0flow.BukkitLoaderPlugin
api-version: '1.13' # We actually support 1.12.2, api-version was added later though
authors: [ Caseload, Axionize ]
description: Synchronizes player knockback for smoother gameplay.
folia-supported: true
depends: ${depends}
permissions:
  neur0flow.update:
    default: op
  neur0flow.toggle.global:
    default: op
  neur0flow.toggle.other:
    default: op
  neur0flow.toggle.self:
    default: op
  neur0flow.ping:
    default: op
  neur0flow.reload:
    default: op
  neur0flow.toggleoffground:
    default: op